Traceback (most recent call last):
  File "C:\Users\doguk\OneDrive\Masaüstü\deppfeakevide\Deep-Fake-Video-Detection\venv\Lib\site-packages\pandas\core\indexes\base.py", line 3805, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'frame'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\doguk\OneDrive\Masaüstü\deppfeakevide\Deep-Fake-Video-Detection\src\train.py", line 97, in <module>
    train(args)
  File "C:\Users\doguk\OneDrive\Masaüstü\deppfeakevide\Deep-Fake-Video-Detection\src\train.py", line 44, in train
    for imgs, labels in train_loader:
  File "C:\Users\doguk\OneDrive\Masaüstü\deppfeakevide\Deep-Fake-Video-Detection\venv\Lib\site-packages\torch\utils\data\dataloader.py", line 633, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\doguk\OneDrive\Masaüstü\deppfeakevide\Deep-Fake-Video-Detection\venv\Lib\site-packages\torch\utils\data\dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\doguk\OneDrive\Masaüstü\deppfeakevide\Deep-Fake-Video-Detection\venv\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\doguk\OneDrive\Masaüstü\deppfeakevide\Deep-Fake-Video-Detection\venv\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "C:\Users\doguk\OneDrive\Masaüstü\deppfeakevide\Deep-Fake-Video-Detection\src\dataset.py", line 25, in __getitem__
    path = os.path.join(self.frames_dir, r['video_id'], f"{r['frame']}.jpg")
                                                           ~^^^^^^^^^
  File "C:\Users\doguk\OneDrive\Masaüstü\deppfeakevide\Deep-Fake-Video-Detection\venv\Lib\site-packages\pandas\core\series.py", line 1121, in __getitem__
    return self._get_value(key)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\doguk\OneDrive\Masaüstü\deppfeakevide\Deep-Fake-Video-Detection\venv\Lib\site-packages\pandas\core\series.py", line 1237, in _get_value
    loc = self.index.get_loc(label)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\doguk\OneDrive\Masaüstü\deppfeakevide\Deep-Fake-Video-Detection\venv\Lib\site-packages\pandas\core\indexes\base.py", line 3812, in get_loc
    raise KeyError(key) from err
KeyError: 'frame'
